### YamlMime:ManagedReference
items:
- uid: AmplifyColor.ResolutionSettings
  commentId: T:AmplifyColor.ResolutionSettings
  id: ResolutionSettings
  parent: AmplifyColor
  children:
  - AmplifyColor.ResolutionSettings.IsCustom
  - AmplifyColor.ResolutionSettings.ResolutionOptions
  - AmplifyColor.ResolutionSettings.SelectedResolution
  - AmplifyColor.ResolutionSettings.TargetHeight
  - AmplifyColor.ResolutionSettings.TargetWidth
  langs:
  - csharp
  - vb
  name: ResolutionSettings
  nameWithType: ResolutionSettings
  fullName: AmplifyColor.ResolutionSettings
  type: Class
  source:
    id: ResolutionSettings
    path: C:\UnityProjects\Figure Shop Simulator\Assets\AmplifyColor\Plugins\Editor\ResolutionSettings.cs
    startLine: 5
  assemblies:
  - Assembly-CSharp-Editor
  namespace: AmplifyColor
  syntax:
    content: public class ResolutionSettings
    content.vb: Public Class ResolutionSettings
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: AmplifyColor.ResolutionSettings.TargetWidth
  commentId: P:AmplifyColor.ResolutionSettings.TargetWidth
  id: TargetWidth
  parent: AmplifyColor.ResolutionSettings
  langs:
  - csharp
  - vb
  name: TargetWidth
  nameWithType: ResolutionSettings.TargetWidth
  fullName: AmplifyColor.ResolutionSettings.TargetWidth
  type: Property
  source:
    id: TargetWidth
    path: C:\UnityProjects\Figure Shop Simulator\Assets\AmplifyColor\Plugins\Editor\ResolutionSettings.cs
    startLine: 23
  assemblies:
  - Assembly-CSharp-Editor
  namespace: AmplifyColor
  syntax:
    content: public int TargetWidth { get; set; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Property TargetWidth As Integer
  overload: AmplifyColor.ResolutionSettings.TargetWidth*
- uid: AmplifyColor.ResolutionSettings.TargetHeight
  commentId: P:AmplifyColor.ResolutionSettings.TargetHeight
  id: TargetHeight
  parent: AmplifyColor.ResolutionSettings
  langs:
  - csharp
  - vb
  name: TargetHeight
  nameWithType: ResolutionSettings.TargetHeight
  fullName: AmplifyColor.ResolutionSettings.TargetHeight
  type: Property
  source:
    id: TargetHeight
    path: C:\UnityProjects\Figure Shop Simulator\Assets\AmplifyColor\Plugins\Editor\ResolutionSettings.cs
    startLine: 33
  assemblies:
  - Assembly-CSharp-Editor
  namespace: AmplifyColor
  syntax:
    content: public int TargetHeight { get; set; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Property TargetHeight As Integer
  overload: AmplifyColor.ResolutionSettings.TargetHeight*
- uid: AmplifyColor.ResolutionSettings.SelectedResolution
  commentId: P:AmplifyColor.ResolutionSettings.SelectedResolution
  id: SelectedResolution
  parent: AmplifyColor.ResolutionSettings
  langs:
  - csharp
  - vb
  name: SelectedResolution
  nameWithType: ResolutionSettings.SelectedResolution
  fullName: AmplifyColor.ResolutionSettings.SelectedResolution
  type: Property
  source:
    id: SelectedResolution
    path: C:\UnityProjects\Figure Shop Simulator\Assets\AmplifyColor\Plugins\Editor\ResolutionSettings.cs
    startLine: 43
  assemblies:
  - Assembly-CSharp-Editor
  namespace: AmplifyColor
  syntax:
    content: public int SelectedResolution { get; set; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Property SelectedResolution As Integer
  overload: AmplifyColor.ResolutionSettings.SelectedResolution*
- uid: AmplifyColor.ResolutionSettings.IsCustom
  commentId: P:AmplifyColor.ResolutionSettings.IsCustom
  id: IsCustom
  parent: AmplifyColor.ResolutionSettings
  langs:
  - csharp
  - vb
  name: IsCustom
  nameWithType: ResolutionSettings.IsCustom
  fullName: AmplifyColor.ResolutionSettings.IsCustom
  type: Property
  source:
    id: IsCustom
    path: C:\UnityProjects\Figure Shop Simulator\Assets\AmplifyColor\Plugins\Editor\ResolutionSettings.cs
    startLine: 54
  assemblies:
  - Assembly-CSharp-Editor
  namespace: AmplifyColor
  syntax:
    content: public bool IsCustom { get; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public ReadOnly Property IsCustom As Boolean
  overload: AmplifyColor.ResolutionSettings.IsCustom*
- uid: AmplifyColor.ResolutionSettings.ResolutionOptions
  commentId: P:AmplifyColor.ResolutionSettings.ResolutionOptions
  id: ResolutionOptions
  parent: AmplifyColor.ResolutionSettings
  langs:
  - csharp
  - vb
  name: ResolutionOptions
  nameWithType: ResolutionSettings.ResolutionOptions
  fullName: AmplifyColor.ResolutionSettings.ResolutionOptions
  type: Property
  source:
    id: ResolutionOptions
    path: C:\UnityProjects\Figure Shop Simulator\Assets\AmplifyColor\Plugins\Editor\ResolutionSettings.cs
    startLine: 59
  assemblies:
  - Assembly-CSharp-Editor
  namespace: AmplifyColor
  syntax:
    content: public string[] ResolutionOptions { get; }
    parameters: []
    return:
      type: System.String[]
    content.vb: Public ReadOnly Property ResolutionOptions As String()
  overload: AmplifyColor.ResolutionSettings.ResolutionOptions*
references:
- uid: AmplifyColor
  commentId: N:AmplifyColor
  href: AmplifyColor.html
  name: AmplifyColor
  nameWithType: AmplifyColor
  fullName: AmplifyColor
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: AmplifyColor.ResolutionSettings.TargetWidth*
  commentId: Overload:AmplifyColor.ResolutionSettings.TargetWidth
  href: AmplifyColor.ResolutionSettings.html#AmplifyColor_ResolutionSettings_TargetWidth
  name: TargetWidth
  nameWithType: ResolutionSettings.TargetWidth
  fullName: AmplifyColor.ResolutionSettings.TargetWidth
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.int32
  name: int
  nameWithType: int
  fullName: int
  nameWithType.vb: Integer
  fullName.vb: Integer
  name.vb: Integer
- uid: AmplifyColor.ResolutionSettings.TargetHeight*
  commentId: Overload:AmplifyColor.ResolutionSettings.TargetHeight
  href: AmplifyColor.ResolutionSettings.html#AmplifyColor_ResolutionSettings_TargetHeight
  name: TargetHeight
  nameWithType: ResolutionSettings.TargetHeight
  fullName: AmplifyColor.ResolutionSettings.TargetHeight
- uid: AmplifyColor.ResolutionSettings.SelectedResolution*
  commentId: Overload:AmplifyColor.ResolutionSettings.SelectedResolution
  href: AmplifyColor.ResolutionSettings.html#AmplifyColor_ResolutionSettings_SelectedResolution
  name: SelectedResolution
  nameWithType: ResolutionSettings.SelectedResolution
  fullName: AmplifyColor.ResolutionSettings.SelectedResolution
- uid: AmplifyColor.ResolutionSettings.IsCustom*
  commentId: Overload:AmplifyColor.ResolutionSettings.IsCustom
  href: AmplifyColor.ResolutionSettings.html#AmplifyColor_ResolutionSettings_IsCustom
  name: IsCustom
  nameWithType: ResolutionSettings.IsCustom
  fullName: AmplifyColor.ResolutionSettings.IsCustom
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.boolean
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
- uid: AmplifyColor.ResolutionSettings.ResolutionOptions*
  commentId: Overload:AmplifyColor.ResolutionSettings.ResolutionOptions
  href: AmplifyColor.ResolutionSettings.html#AmplifyColor_ResolutionSettings_ResolutionOptions
  name: ResolutionOptions
  nameWithType: ResolutionSettings.ResolutionOptions
  fullName: AmplifyColor.ResolutionSettings.ResolutionOptions
- uid: System.String[]
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string[]
  nameWithType: string[]
  fullName: string[]
  nameWithType.vb: String()
  fullName.vb: String()
  name.vb: String()
  spec.csharp:
  - uid: System.String
    name: string
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: '['
  - name: ']'
  spec.vb:
  - uid: System.String
    name: String
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: (
  - name: )
