### YamlMime:ManagedReference
items:
- uid: AmplifyColor.ToolSettings
  commentId: T:AmplifyColor.ToolSettings
  id: ToolSettings
  parent: AmplifyColor
  children:
  - AmplifyColor.ToolSettings.AddLut
  - AmplifyColor.ToolSettings.ApplyColorGrading
  - AmplifyColor.ToolSettings.ApplyHDRControl
  - AmplifyColor.ToolSettings.FilePath
  - AmplifyColor.ToolSettings.Host
  - AmplifyColor.ToolSettings.Instance
  - AmplifyColor.ToolSettings.LUT
  - AmplifyColor.ToolSettings.Message
  - AmplifyColor.ToolSettings.Password
  - AmplifyColor.ToolSettings.Resolution
  - AmplifyColor.ToolSettings.SelectedTab
  langs:
  - csharp
  - vb
  name: ToolSettings
  nameWithType: ToolSettings
  fullName: AmplifyColor.ToolSettings
  type: Class
  source:
    id: ToolSettings
    path: C:\UnityProjects\Figure Shop Simulator\Assets\AmplifyColor\Plugins\Editor\ToolSettings.cs
    startLine: 7
  assemblies:
  - Assembly-CSharp-Editor
  namespace: AmplifyColor
  syntax:
    content: public class ToolSettings
    content.vb: Public Class ToolSettings
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: AmplifyColor.ToolSettings.AddLut
  commentId: F:AmplifyColor.ToolSettings.AddLut
  id: AddLut
  parent: AmplifyColor.ToolSettings
  langs:
  - csharp
  - vb
  name: AddLut
  nameWithType: ToolSettings.AddLut
  fullName: AmplifyColor.ToolSettings.AddLut
  type: Field
  source:
    id: AddLut
    path: C:\UnityProjects\Figure Shop Simulator\Assets\AmplifyColor\Plugins\Editor\ToolSettings.cs
    startLine: 10
  assemblies:
  - Assembly-CSharp-Editor
  namespace: AmplifyColor
  syntax:
    content: public bool AddLut
    return:
      type: System.Boolean
    content.vb: Public AddLut As Boolean
- uid: AmplifyColor.ToolSettings.ApplyHDRControl
  commentId: F:AmplifyColor.ToolSettings.ApplyHDRControl
  id: ApplyHDRControl
  parent: AmplifyColor.ToolSettings
  langs:
  - csharp
  - vb
  name: ApplyHDRControl
  nameWithType: ToolSettings.ApplyHDRControl
  fullName: AmplifyColor.ToolSettings.ApplyHDRControl
  type: Field
  source:
    id: ApplyHDRControl
    path: C:\UnityProjects\Figure Shop Simulator\Assets\AmplifyColor\Plugins\Editor\ToolSettings.cs
    startLine: 11
  assemblies:
  - Assembly-CSharp-Editor
  namespace: AmplifyColor
  syntax:
    content: public bool ApplyHDRControl
    return:
      type: System.Boolean
    content.vb: Public ApplyHDRControl As Boolean
- uid: AmplifyColor.ToolSettings.ApplyColorGrading
  commentId: F:AmplifyColor.ToolSettings.ApplyColorGrading
  id: ApplyColorGrading
  parent: AmplifyColor.ToolSettings
  langs:
  - csharp
  - vb
  name: ApplyColorGrading
  nameWithType: ToolSettings.ApplyColorGrading
  fullName: AmplifyColor.ToolSettings.ApplyColorGrading
  type: Field
  source:
    id: ApplyColorGrading
    path: C:\UnityProjects\Figure Shop Simulator\Assets\AmplifyColor\Plugins\Editor\ToolSettings.cs
    startLine: 12
  assemblies:
  - Assembly-CSharp-Editor
  namespace: AmplifyColor
  syntax:
    content: public bool ApplyColorGrading
    return:
      type: System.Boolean
    content.vb: Public ApplyColorGrading As Boolean
- uid: AmplifyColor.ToolSettings.FilePath
  commentId: F:AmplifyColor.ToolSettings.FilePath
  id: FilePath
  parent: AmplifyColor.ToolSettings
  langs:
  - csharp
  - vb
  name: FilePath
  nameWithType: ToolSettings.FilePath
  fullName: AmplifyColor.ToolSettings.FilePath
  type: Field
  source:
    id: FilePath
    path: C:\UnityProjects\Figure Shop Simulator\Assets\AmplifyColor\Plugins\Editor\ToolSettings.cs
    startLine: 13
  assemblies:
  - Assembly-CSharp-Editor
  namespace: AmplifyColor
  syntax:
    content: public string FilePath
    return:
      type: System.String
    content.vb: Public FilePath As String
- uid: AmplifyColor.ToolSettings.Host
  commentId: F:AmplifyColor.ToolSettings.Host
  id: Host
  parent: AmplifyColor.ToolSettings
  langs:
  - csharp
  - vb
  name: Host
  nameWithType: ToolSettings.Host
  fullName: AmplifyColor.ToolSettings.Host
  type: Field
  source:
    id: Host
    path: C:\UnityProjects\Figure Shop Simulator\Assets\AmplifyColor\Plugins\Editor\ToolSettings.cs
    startLine: 15
  assemblies:
  - Assembly-CSharp-Editor
  namespace: AmplifyColor
  syntax:
    content: public string Host
    return:
      type: System.String
    content.vb: Public Host As String
- uid: AmplifyColor.ToolSettings.LUT
  commentId: F:AmplifyColor.ToolSettings.LUT
  id: LUT
  parent: AmplifyColor.ToolSettings
  langs:
  - csharp
  - vb
  name: LUT
  nameWithType: ToolSettings.LUT
  fullName: AmplifyColor.ToolSettings.LUT
  type: Field
  source:
    id: LUT
    path: C:\UnityProjects\Figure Shop Simulator\Assets\AmplifyColor\Plugins\Editor\ToolSettings.cs
    startLine: 16
  assemblies:
  - Assembly-CSharp-Editor
  namespace: AmplifyColor
  syntax:
    content: public LUTSettings LUT
    return:
      type: AmplifyColor.LUTSettings
    content.vb: Public LUT As LUTSettings
- uid: AmplifyColor.ToolSettings.Message
  commentId: F:AmplifyColor.ToolSettings.Message
  id: Message
  parent: AmplifyColor.ToolSettings
  langs:
  - csharp
  - vb
  name: Message
  nameWithType: ToolSettings.Message
  fullName: AmplifyColor.ToolSettings.Message
  type: Field
  source:
    id: Message
    path: C:\UnityProjects\Figure Shop Simulator\Assets\AmplifyColor\Plugins\Editor\ToolSettings.cs
    startLine: 18
  assemblies:
  - Assembly-CSharp-Editor
  namespace: AmplifyColor
  syntax:
    content: public string Message
    return:
      type: System.String
    content.vb: Public Message As String
- uid: AmplifyColor.ToolSettings.Password
  commentId: F:AmplifyColor.ToolSettings.Password
  id: Password
  parent: AmplifyColor.ToolSettings
  langs:
  - csharp
  - vb
  name: Password
  nameWithType: ToolSettings.Password
  fullName: AmplifyColor.ToolSettings.Password
  type: Field
  source:
    id: Password
    path: C:\UnityProjects\Figure Shop Simulator\Assets\AmplifyColor\Plugins\Editor\ToolSettings.cs
    startLine: 19
  assemblies:
  - Assembly-CSharp-Editor
  namespace: AmplifyColor
  syntax:
    content: public string Password
    return:
      type: System.String
    content.vb: Public Password As String
- uid: AmplifyColor.ToolSettings.Resolution
  commentId: F:AmplifyColor.ToolSettings.Resolution
  id: Resolution
  parent: AmplifyColor.ToolSettings
  langs:
  - csharp
  - vb
  name: Resolution
  nameWithType: ToolSettings.Resolution
  fullName: AmplifyColor.ToolSettings.Resolution
  type: Field
  source:
    id: Resolution
    path: C:\UnityProjects\Figure Shop Simulator\Assets\AmplifyColor\Plugins\Editor\ToolSettings.cs
    startLine: 21
  assemblies:
  - Assembly-CSharp-Editor
  namespace: AmplifyColor
  syntax:
    content: public ResolutionSettings Resolution
    return:
      type: AmplifyColor.ResolutionSettings
    content.vb: Public Resolution As ResolutionSettings
- uid: AmplifyColor.ToolSettings.SelectedTab
  commentId: F:AmplifyColor.ToolSettings.SelectedTab
  id: SelectedTab
  parent: AmplifyColor.ToolSettings
  langs:
  - csharp
  - vb
  name: SelectedTab
  nameWithType: ToolSettings.SelectedTab
  fullName: AmplifyColor.ToolSettings.SelectedTab
  type: Field
  source:
    id: SelectedTab
    path: C:\UnityProjects\Figure Shop Simulator\Assets\AmplifyColor\Plugins\Editor\ToolSettings.cs
    startLine: 23
  assemblies:
  - Assembly-CSharp-Editor
  namespace: AmplifyColor
  syntax:
    content: public int SelectedTab
    return:
      type: System.Int32
    content.vb: Public SelectedTab As Integer
- uid: AmplifyColor.ToolSettings.Instance
  commentId: P:AmplifyColor.ToolSettings.Instance
  id: Instance
  parent: AmplifyColor.ToolSettings
  langs:
  - csharp
  - vb
  name: Instance
  nameWithType: ToolSettings.Instance
  fullName: AmplifyColor.ToolSettings.Instance
  type: Property
  source:
    id: Instance
    path: C:\UnityProjects\Figure Shop Simulator\Assets\AmplifyColor\Plugins\Editor\ToolSettings.cs
    startLine: 43
  assemblies:
  - Assembly-CSharp-Editor
  namespace: AmplifyColor
  syntax:
    content: public static ToolSettings Instance { get; }
    parameters: []
    return:
      type: AmplifyColor.ToolSettings
    content.vb: Public Shared ReadOnly Property Instance As ToolSettings
  overload: AmplifyColor.ToolSettings.Instance*
references:
- uid: AmplifyColor
  commentId: N:AmplifyColor
  href: AmplifyColor.html
  name: AmplifyColor
  nameWithType: AmplifyColor
  fullName: AmplifyColor
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.boolean
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: AmplifyColor.LUTSettings
  commentId: T:AmplifyColor.LUTSettings
  parent: AmplifyColor
  href: AmplifyColor.LUTSettings.html
  name: LUTSettings
  nameWithType: LUTSettings
  fullName: AmplifyColor.LUTSettings
- uid: AmplifyColor.ResolutionSettings
  commentId: T:AmplifyColor.ResolutionSettings
  parent: AmplifyColor
  href: AmplifyColor.ResolutionSettings.html
  name: ResolutionSettings
  nameWithType: ResolutionSettings
  fullName: AmplifyColor.ResolutionSettings
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.int32
  name: int
  nameWithType: int
  fullName: int
  nameWithType.vb: Integer
  fullName.vb: Integer
  name.vb: Integer
- uid: AmplifyColor.ToolSettings.Instance*
  commentId: Overload:AmplifyColor.ToolSettings.Instance
  href: AmplifyColor.ToolSettings.html#AmplifyColor_ToolSettings_Instance
  name: Instance
  nameWithType: ToolSettings.Instance
  fullName: AmplifyColor.ToolSettings.Instance
- uid: AmplifyColor.ToolSettings
  commentId: T:AmplifyColor.ToolSettings
  parent: AmplifyColor
  href: AmplifyColor.ToolSettings.html
  name: ToolSettings
  nameWithType: ToolSettings
  fullName: AmplifyColor.ToolSettings
